### ISSUE TITLE
Add Redis accessory

### ISSUE THREAD

**Issue by nicogaldamez** [unagisoftware/kamalify#41]
## Why

* Many users rely on Redis as a core dependency in their projects.

## What

* The Redis accessory should be optional
* Add a new toggle "Include a Redis accessory" under _Accessories_ section
* When enabled, display the following input fields:
  * **image**: defaults to `redis:latest`
  * **port**: defaults to `6379`
  * **roles**: defaults to `web`. Allow multiple roles
  * **cmd**: defaults to `/bin/sh -c 'redis-server --requirepass $REDIS_PASSWORD'`

Once configured, the final output should look like this:

```yml
redis:
    image: redis:latest
    port: 6379
    roles:
      - web
      - job
    cmd: "/bin/sh -c 'redis-server --requirepass $REDIS_PASSWORD'"
    volumes:
      - /var/lib/redis:/data
    env:
      secret:
        - REDIS_PASSWORD
 ```

`Volumes` and `env` could be added automatically.
